### ISSUE TITLE
Whups! Ubuntu a no-fly zone? (Or is it me?)

### ISSUE THREAD

**Issue by iDGS** [dsparks83/statamic-word-truncate#2]
See trouble with different environment noted here: [https://lodge.statamic.com/support/1967-got-a-closetags-modifier-or-equivalent#reply-21](https://lodge.statamic.com/support/1967-got-a-closetags-modifier-or-equivalent#reply-21)

**Comment by dsparks83** [comment]
I'm not sure on this one, it's strange that it's spitting out the code from partway down in the error. 
The truncate bit is lifted from the actual statamic plugin so that should be fine, the other bit is reasonably standard PHP, I can't see anything obvious that'd cause trouble.
I've put an unrelated update on github so maybe try that and see if you could see if the close tags on it's own has any issues that'd be helpful - https://github.com/dsparks83/Statamic-Close-Tags

**Comment by iDGS** [comment]
Thanks! I like the roll-your-own-ending thing very much!

Other things are still busted wrt my server/staging environment, though. Here's some more (hopefully helpful) info: [https://lodge.statamic.com/support/1967-got-a-closetags-modifier-or-equivalent#reply-24](https://lodge.statamic.com/support/1967-got-a-closetags-modifier-or-equivalent#reply-24)

**Comment by dsparks83** [comment]
Corrected, needed long form <?php braces
